"""empty message

Revision ID: bcf9ffcf2fa6
Revises: 
Create Date: 2026-04-03 13:08:44.910806

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bcf9ffcf2fa6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Books')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Books',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', mysql.VARCHAR(length=80), nullable=False),
    sa.Column('author', mysql.VARCHAR(length=80), nullable=False),
    sa.Column('price', mysql.FLOAT(), nullable=False),
    sa.Column('condition', mysql.VARCHAR(length=80), nullable=False),
    sa.Column('grade', mysql.VARCHAR(length=80), nullable=True),
    sa.Column('subject', mysql.VARCHAR(length=80), nullable=True),
    sa.Column('quantity', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
